### ISSUE TITLE
Python Port

### ISSUE THREAD

**Issue by pedro2555** [JordannDev/VatsimMemberAPI#2]
Hi,

We've got in touch on the VATSIM Forums. I have a running project to gather various VATSIM data tools I've been developing for myself.

https://github.com/pedro2555/vatsim-api

At the moment we have status data information, but we have a roapmap for much more:
 * Events (coming next month, a dedicated API is live for a while, will be ported over) https://github.com/pedro2555/vateud-events-api
 * GNG Sector information (provides proper area highlight, with GEOJson features)
 * ATC Bookings

I've never though about the members, but I would very much love to have such function.

The project is fully written in Python. If you are familiar with Python, I would like to propose to you a port of your API to mine, and I can create a Java library to access my API (probably something I want to do anyway, since android is so widely used) leveraging Retrofit most likely.

I known its a weird proposition, has is my API, its a bit of children of mine, but at the same time never hurts to ask. Let me known what you think.

Regards

**Comment by JordannDev** [comment]
Hi Pedro,

Unfortunately I don't know Python. But if you want to port my API feel free. I
think you would be better off using your vACC's dedicated API (if you have
one), you would have access to a lot more information. The VATSIM API I am
using is being retired soon, so we don't really know what will be next. The
VatsimMemberAPI I wrote only has access to Vatsim specific information,
compared to a division site you would get a lot more information.

- Jordan.

**Comment by pedro2555** [comment]
Ok,

Fair enough. be aware I will be porting your functionality into my own API. You'll be credited with a Java version as the base work, tell me if your not OK with credits to you.

VATSIM API is not affiliated to any vAcc, its a product of mine provided free and open source. (It just so happens that the ATIS system at Portugal's vAcc is using it)

The general plan with my project, is not only provide an API service, but also provide general usage client libraries (or examples at the very least) for the wider cases (Java because of Android, Python a widely used general purpose language, C# for the .NET world, and Javascript which will start as Vatsim Radar/Map online that is in the works at this moment).

Java is most likely to leverage the Retrofit library. If you're interested in participating in the project feel free to contact me.
